var ios_breakfast = [{"rank":1,"description":"Coffee - Brewed from grounds","brand":""},
{"rank":2,"description":"Quick Added Calories","brand":""},
{"rank":3,"description":"Milk - Nonfat (fat free or skim)","brand":""},
{"rank":4,"description":"Milk - Reduced fat, 2% milkfat","brand":""},
{"rank":5,"description":"Eggs - Fried (whole egg)","brand":""},
{"rank":6,"description":"Strawberries - Raw","brand":""},
{"rank":7,"description":"Blueberries - Raw","brand":""},
{"rank":8,"description":"Bread - Whole-wheat, toasted","brand":""},
{"rank":9,"description":"Eggs - Scrambled (whole egg)","brand":""},
{"rank":10,"description":"Cream - Half and half","brand":""},
{"rank":11,"description":"Eggs - Poached (whole egg)","brand":""},
{"rank":12,"description":"Spinach - Raw","brand":""},
{"rank":13,"description":"Raspberries - Raw","brand":""},
{"rank":14,"description":"Pork - Cured, bacon, cooked, pan-fried","brand":""},
{"rank":15,"description":"Apples - Raw, with skin","brand":""},
{"rank":16,"description":"Bananas - Raw","brand":""},
{"rank":17,"description":"Cereals - Oats, regular and quick and instant, unenriched, cooked with water, without salt (oatmeal)","brand":""},
{"rank":18,"description":"Butter - Salted","brand":""},
{"rank":19,"description":"Milk - Whole, 3.25% milkfat","brand":""},
{"rank":20,"description":"Banana","brand":"Dole Costco"},
{"rank":21,"description":"Honey","brand":""},
{"rank":22,"description":"Pineapple - Raw, all varieties","brand":""},
{"rank":23,"description":"Blackberries - Raw","brand":""},
{"rank":24,"description":"Tea - Brewed, prepared with tap water (black tea)","brand":""},
{"rank":25,"description":"Spices - Cinnamon, ground","brand":""},
{"rank":26,"description":"Blueberries - Frozen, unsweetened","brand":""},
{"rank":27,"description":"Coffee - Instant, regular","brand":""},
{"rank":28,"description":"Oranges - Raw, navels","brand":""},
{"rank":29,"description":"Bread - White, toasted","brand":""},
{"rank":30,"description":"Mushrooms - Raw","brand":""},
{"rank":31,"description":"Fresh Milk Semi-skimmed","brand":"Daily Milk"},
{"rank":32,"description":"Onions - Raw","brand":""},
{"rank":33,"description":"Eggs - Hard-boiled (whole egg)","brand":""},
{"rank":34,"description":"Oil - Olive","brand":""},
{"rank":35,"description":"Orange juice - Chilled, includes from concentrate","brand":""},
{"rank":36,"description":"Kale - Raw","brand":""},
{"rank":37,"description":"Watermelon - Raw","brand":""},
{"rank":38,"description":"Grapes - Raw","brand":""},
{"rank":39,"description":"Melons - Cantaloupe, raw","brand":""},
{"rank":40,"description":"Ham - Sliced, extra lean","brand":""},
{"rank":41,"description":"Sugars - Granulated (sucrose)","brand":""},
{"rank":42,"description":"Sugars - Brown","brand":""},
{"rank":43,"description":"Pancakes - Plain","brand":""},
{"rank":44,"description":"Pork sausage - Fresh, cooked","brand":""},
{"rank":45,"description":"Coffee - Brewed, espresso","brand":""},
{"rank":46,"description":"Bread - Whole-wheat","brand":""},
{"rank":47,"description":"Orange Juice","brand":"Tropicana"},
{"rank":48,"description":"Bread - Rye, toasted","brand":""},
{"rank":49,"description":"Banana, Small","brand":"Fruit"},
{"rank":50,"description":"Biscuits - Plain or buttermilk, baked","brand":""},
{"rank":51,"description":"Half and Half","brand":"Land O Lakes"},
{"rank":52,"description":"Rice - White, long-grain, regular, cooked","brand":""},
{"rank":53,"description":"Bread - Mixed-grain, toasted (includes whole-grain, 7-grain)","brand":""},
{"rank":54,"description":"Tea With Semi Skimmed Milk","brand":"Tetley"},
{"rank":55,"description":"Mangos - Raw","brand":""},
{"rank":56,"description":"Tea With 50ml Semi-Skimmed Milk","brand":"Generic"},
{"rank":57,"description":"1% Lowfat Milk","brand":"Welsh Farms"},
{"rank":58,"description":"Egg White","brand":"Mc - Egg Whites"},
{"rank":59,"description":"Banana","brand":"Dole Costco"},
{"rank":60,"description":"Water - Municipal","brand":""},
{"rank":61,"description":"Banana","brand":"Francis"},
{"rank":62,"description":"Cucumber - With peel, raw","brand":""},
{"rank":63,"description":"Tea With Semi Skimmed Milk","brand":"Tetley"},
{"rank":64,"description":"Carrots - Raw","brand":""},
{"rank":65,"description":"2 Scrambled Eggs, Plain","brand":"Country Crock Margarine"},
{"rank":66,"description":"Wholemeal Bread Toasted","brand":"Hovis (Uk"},
{"rank":67,"description":"Cherries - Sweet, raw","brand":""},
{"rank":68,"description":"Skimmed Milk","brand":"Tesco"},
{"rank":69,"description":"Butter - Unsalted","brand":""},
{"rank":70,"description":"Runny Honey","brand":"Sainsbury's"},
{"rank":71,"description":"Milk - Chocolate","brand":""},
{"rank":72,"description":"Medium Banana","brand":"Kwik Trip"},
{"rank":73,"description":"Cup of Tea With Skimmed Milk","brand":"Tea"},
{"rank":74,"description":"Ham - Sliced, regular (approximately 11% fat)","brand":""},
{"rank":75,"description":"Tea With Semi Skimmed Milk","brand":"Tetley"},
{"rank":76,"description":"Orange juice - Raw","brand":""},
{"rank":77,"description":"Banana","brand":"Generic"},
{"rank":78,"description":"Strawberries - Frozen, unsweetened","brand":""},
{"rank":79,"description":"Coffee With Skimmed Milk","brand":"Home Prepared"},
{"rank":80,"description":"Melons - Honeydew, raw","brand":""},
{"rank":81,"description":"Cottage cheese - Lowfat, 2% milkfat","brand":""},
{"rank":82,"description":"1% Lowfat Milk","brand":"Schnucks"},
{"rank":83,"description":"Tea With Semi Skimmed Milk","brand":"Tetley"},
{"rank":84,"description":"Muesli - dried fruit and nuts","brand":""},
{"rank":85,"description":"Sugar 3 Teaspoon","brand":"Lantic"},
{"rank":86,"description":"Organic Chia Seeds","brand":"Mountain Rose"},
{"rank":87,"description":"Honey Bunches of Oats With Almonds","brand":"Post"},
{"rank":88,"description":"Banana","brand":"Generic"},
{"rank":89,"description":"Egg","brand":"Martin"},
{"rank":90,"description":"Jams and preserves","brand":""},
{"rank":91,"description":"Banana","brand":"Produce"},
{"rank":92,"description":"Tea With Semi Skimmed Milk","brand":"Tetley Tea"},
{"rank":93,"description":"Skimmed Milk (2.27 Litres / 4 Pints Carton)","brand":"Tesco"},
{"rank":94,"description":"Cup of Tea, Semi Skim Milk","brand":"Drinks"},
{"rank":95,"description":"Sugar 3 Teaspoon","brand":"Lantic"},
{"rank":96,"description":"Coffee Creamer ~ Caramel Macchiato","brand":"International Delight"},
{"rank":97,"description":"Peaches - Raw","brand":""},
{"rank":98,"description":"Nuts - Almonds","brand":""},
{"rank":99,"description":"Tea With Semi Skimmed Milk","brand":"Tetley"},
{"rank":100,"description":"Coffee With 2% Milk","brand":"Generic"}];

var android_breakfast = [{"rank":1,"description":"Coffee - Brewed from grounds","brand":""},
{"rank":2,"description":"Quick Added Calories","brand":""},
{"rank":3,"description":"Milk - Nonfat (fat free or skim)","brand":""},
{"rank":4,"description":"Milk - Reduced fat, 2% milkfat","brand":""},
{"rank":5,"description":"Eggs - Fried (whole egg)","brand":""},
{"rank":6,"description":"Strawberries - Raw","brand":""},
{"rank":7,"description":"Blueberries - Raw","brand":""},
{"rank":8,"description":"Bread - Whole-wheat, toasted","brand":""},
{"rank":9,"description":"Eggs - Scrambled (whole egg)","brand":""},
{"rank":10,"description":"Pork - Cured, bacon, cooked, pan-fried","brand":""},
{"rank":11,"description":"Milk - Whole, 3.25% milkfat","brand":""},
{"rank":12,"description":"Apples - Raw, with skin","brand":""},
{"rank":13,"description":"Spinach - Raw","brand":""},
{"rank":14,"description":"Bananas - Raw","brand":""},
{"rank":15,"description":"Cereals - Oats, regular and quick and instant, unenriched, cooked with water, without salt (oatmeal)","brand":""},
{"rank":16,"description":"Cream - Half and half","brand":""},
{"rank":17,"description":"Banana","brand":"Dole Costco"},
{"rank":18,"description":"Butter - Salted","brand":""},
{"rank":19,"description":"Eggs - Poached (whole egg)","brand":""},
{"rank":20,"description":"Raspberries - Raw","brand":""},
{"rank":21,"description":"Honey","brand":""},
{"rank":22,"description":"Pineapple - Raw, all varieties","brand":""},
{"rank":23,"description":"Tea - Brewed, prepared with tap water (black tea)","brand":""},
{"rank":24,"description":"Blackberries - Raw","brand":""},
{"rank":25,"description":"Blueberries - Frozen, unsweetened","brand":""},
{"rank":26,"description":"Coffee - Instant, regular","brand":""},
{"rank":27,"description":"Eggs - Hard-boiled (whole egg)","brand":""},
{"rank":28,"description":"Spices - Cinnamon, ground","brand":""},
{"rank":29,"description":"Oranges - Raw, navels","brand":""},
{"rank":30,"description":"Bread - White, toasted","brand":""},
{"rank":31,"description":"Fresh Milk Semi-skimmed","brand":"Daily Milk"},
{"rank":32,"description":"Onions - Raw","brand":""},
{"rank":33,"description":"Mushrooms - Raw","brand":""},
{"rank":34,"description":"Bread - Whole-wheat","brand":""},
{"rank":35,"description":"Oil - Olive","brand":""},
{"rank":36,"description":"Kale - Raw","brand":""},
{"rank":37,"description":"Watermelon - Raw","brand":""},
{"rank":38,"description":"Sugars - Granulated (sucrose)","brand":""},
{"rank":39,"description":"Grapes - Raw","brand":""},
{"rank":40,"description":"Ham - Sliced, extra lean","brand":""},
{"rank":41,"description":"Biscuits - Plain or buttermilk, baked","brand":""},
{"rank":42,"description":"Pancakes - Plain","brand":""},
{"rank":43,"description":"Orange juice - Chilled, includes from concentrate","brand":""},
{"rank":44,"description":"Rice - White, long-grain, regular, cooked","brand":""},
{"rank":45,"description":"Orange Juice","brand":"Tropicana"},
{"rank":46,"description":"Sugars - Brown","brand":""},
{"rank":47,"description":"1% Lowfat Milk","brand":"Welsh Farms"},
{"rank":48,"description":"Pork sausage - Fresh, cooked","brand":""},
{"rank":49,"description":"Melons - Cantaloupe, raw","brand":""},
{"rank":50,"description":"Half and Half","brand":"Land O Lakes"},
{"rank":51,"description":"Water - Municipal","brand":""},
{"rank":52,"description":"Coffee","brand":"Folgers-Classic Roast Coffee Medium Blend"},
{"rank":53,"description":"Tea With Semi Skimmed Milk","brand":"Tetley"},
{"rank":54,"description":"Banana, Small","brand":"Fruit"},
{"rank":55,"description":"Banana","brand":"Dole Costco"},
{"rank":56,"description":"Tea With Semi Skimmed Milk","brand":"Tetley"},
{"rank":57,"description":"Bread - Rye, toasted","brand":""},
{"rank":58,"description":"Kaffee + H-milch (1,5% Fett)","brand":"Diverse"},
{"rank":59,"description":"Milk - Chocolate","brand":""},
{"rank":60,"description":"Egg White","brand":"Mc - Egg Whites"},
{"rank":61,"description":"Ham - Sliced, regular (approximately 11% fat)","brand":""},
{"rank":62,"description":"Coffee Creamer ~ Caramel Macchiato","brand":"International Delight"},
{"rank":63,"description":"2 Scrambled Eggs, Plain","brand":"Country Crock Margarine"},
{"rank":64,"description":"Coffee - Brewed, espresso","brand":""},
{"rank":65,"description":"Carrots - Raw","brand":""},
{"rank":66,"description":"Cucumber - With peel, raw","brand":""},
{"rank":67,"description":"Butter - Unsalted","brand":""},
{"rank":68,"description":"Sugar 3 Teaspoon","brand":"Lantic"},
{"rank":69,"description":"Honey Bunches of Oats With Almonds","brand":"Post"},
{"rank":70,"description":"1% Lowfat Milk","brand":"Schnucks"},
{"rank":71,"description":"Strawberries - Frozen, unsweetened","brand":""},
{"rank":72,"description":"Cherries - Sweet, raw","brand":""},
{"rank":73,"description":"Banane","brand":"Frucht"},
{"rank":74,"description":"Mangos - Raw","brand":""},
{"rank":75,"description":"Cottage cheese - Lowfat, 2% milkfat","brand":""},
{"rank":76,"description":"Sugar 3 Teaspoon","brand":"Lantic"},
{"rank":77,"description":"Banana","brand":"Francis"},
{"rank":78,"description":"Granulated Sugar (Corrected Per Package Label)","brand":"Great Value"},
{"rank":79,"description":"Sugar for Coffee (or Option for 0.5 Tsp Paper Packet)","brand":"Sugar"},
{"rank":80,"description":"Coffee With Creamer","brand":"Coffee With Coffee Mate Liquid Creamer- Orginial"},
{"rank":81,"description":"Egg","brand":"Martin"},
{"rank":82,"description":"Wholemeal Bread Toasted","brand":"Hovis (Uk"},
{"rank":83,"description":"Banana (Chiquita)","brand":"Banana Mink"},
{"rank":84,"description":"Coffee With 2tbsp Creamer","brand":"Generic"},
{"rank":85,"description":"Medium Banana","brand":"Kwik Trip"},
{"rank":86,"description":"Banana","brand":"Generic"},
{"rank":87,"description":"Rice - White, medium-grain, cooked","brand":""},
{"rank":88,"description":"Banana (7","brand":"Generic Usda"},
{"rank":89,"description":"Bananas","brand":"Dole"},
{"rank":90,"description":"Skimmed Milk","brand":"Tesco"},
{"rank":91,"description":"Coffee With 2% Milk","brand":"Generic"},
{"rank":92,"description":"Chicken - Breast, meat only, cooked, roasted","brand":""},
{"rank":93,"description":"Sugar (Granulated)","brand":"Silver Spoon"},
{"rank":94,"description":"Kaffee Mit Milch (3,5% Fett)","brand":"Generic"},
{"rank":95,"description":"Bread - Mixed-grain, toasted (includes whole-grain, 7-grain)","brand":""},
{"rank":96,"description":"Tea With Semi Skimmed Milk","brand":"Tetley"},
{"rank":97,"description":"Coffee Creamer","brand":"Kroger French Vanilla Creamer(Copied From Label"},
{"rank":98,"description":"Butter","brand":"Aufstrich"},
{"rank":99,"description":"Skimmed Milk (2.27 Litres / 4 Pints Carton)","brand":"Tesco"},
{"rank":100,"description":"Banana (7","brand":"Generic Usda"}];

var windows_breakfast = [{"rank":1,"description":"Coffee - Brewed from grounds","brand":""},
{"rank":2,"description":"Milk - Nonfat (fat free or skim)","brand":""},
{"rank":3,"description":"Milk - Reduced fat, 2% milkfat","brand":""},
{"rank":4,"description":"Eggs - Fried (whole egg)","brand":""},
{"rank":5,"description":"Strawberries - Raw","brand":""},
{"rank":6,"description":"Blueberries - Raw","brand":""},
{"rank":7,"description":"Bread - Whole-wheat, toasted","brand":""},
{"rank":8,"description":"Eggs - Scrambled (whole egg)","brand":""},
{"rank":9,"description":"Quick Added Calories","brand":""},
{"rank":10,"description":"Pork - Cured, bacon, cooked, pan-fried","brand":""},
{"rank":11,"description":"Milk - Whole, 3.25% milkfat","brand":""},
{"rank":12,"description":"Apples - Raw, with skin","brand":""},
{"rank":13,"description":"Bananas - Raw","brand":""},
{"rank":14,"description":"Cereals - Oats, regular and quick and instant, unenriched, cooked with water, without salt (oatmeal)","brand":""},
{"rank":15,"description":"Cream - Half and half","brand":""},
{"rank":16,"description":"Fresh Milk Semi-skimmed","brand":"Daily Milk"},
{"rank":17,"description":"Eggs - Poached (whole egg)","brand":""},
{"rank":18,"description":"Butter - Salted","brand":""},
{"rank":19,"description":"Spinach - Raw","brand":""},
{"rank":20,"description":"Banana","brand":"Dole Costco"},
{"rank":21,"description":"Raspberries - Raw","brand":""},
{"rank":22,"description":"Tea - Brewed, prepared with tap water (black tea)","brand":""},
{"rank":23,"description":"Honey","brand":""},
{"rank":24,"description":"Pineapple - Raw, all varieties","brand":""},
{"rank":25,"description":"Blueberries - Frozen, unsweetened","brand":""},
{"rank":26,"description":"Coffee - Instant, regular","brand":""},
{"rank":27,"description":"Blackberries - Raw","brand":""},
{"rank":28,"description":"Banana, Small","brand":"Fruit"},
{"rank":29,"description":"Bread - White, toasted","brand":""},
{"rank":30,"description":"Eggs - Hard-boiled (whole egg)","brand":""},
{"rank":31,"description":"Tea With Semi Skimmed Milk","brand":"Tetley"},
{"rank":32,"description":"Tea With Semi Skimmed Milk","brand":"Tetley"},
{"rank":33,"description":"Tea With Semi Skimmed Milk","brand":"Tetley"},
{"rank":34,"description":"Oranges - Raw, navels","brand":""},
{"rank":35,"description":"Spices - Cinnamon, ground","brand":""},
{"rank":36,"description":"Skimmed Milk","brand":"Tesco"},
{"rank":37,"description":"Orange Juice","brand":"Tropicana"},
{"rank":38,"description":"Bread - Whole-wheat","brand":""},
{"rank":39,"description":"Oil - Olive","brand":""},
{"rank":40,"description":"Onions - Raw","brand":""},
{"rank":41,"description":"Sugars - Granulated (sucrose)","brand":""},
{"rank":42,"description":"Skimmed Milk (2.27 Litres / 4 Pints Carton)","brand":"Tesco"},
{"rank":43,"description":"Wholemeal Bread Toasted","brand":"Hovis (Uk"},
{"rank":44,"description":"Mushrooms - Raw","brand":""},
{"rank":45,"description":"Pork sausage - Fresh, cooked","brand":""},
{"rank":46,"description":"Coffee Instant Made With Water & Semi Skimmed Milk 400mls","brand":"Home Prepared"},
{"rank":47,"description":"Sugar (Granulated)","brand":"Silver Spoon"},
{"rank":48,"description":"Grapes - Raw","brand":""},
{"rank":49,"description":"Pancakes - Plain","brand":""},
{"rank":50,"description":"Coffee With 2% Milk","brand":"Generic"},
{"rank":51,"description":"Banana","brand":"Francis"},
{"rank":52,"description":"1% Lowfat Milk","brand":"Welsh Farms"},
{"rank":53,"description":"Kale - Raw","brand":""},
{"rank":54,"description":"Orange juice - Chilled, includes from concentrate","brand":""},
{"rank":55,"description":"Mug Instant Coffee With Skimmed Milk","brand":"Coffee"},
{"rank":56,"description":"Sugar for Coffee (or Option for 0.5 Tsp Paper Packet)","brand":"Sugar"},
{"rank":57,"description":"Ham - Sliced, extra lean","brand":""},
{"rank":58,"description":"Runny Honey","brand":"Sainsbury's"},
{"rank":59,"description":"Rice - White, long-grain, regular, cooked","brand":""},
{"rank":60,"description":"Watermelon - Raw","brand":""},
{"rank":61,"description":"Half and Half","brand":"Land O Lakes"},
{"rank":62,"description":"Mug of Tea, Skimmed Milk. 1 Sugar","brand":"Pg Tips Jan 2012"},
{"rank":63,"description":"Tea (With Semi Skimmed Milk)","brand":"Tea"},
{"rank":64,"description":"Coffee Creamer ~ Caramel Macchiato","brand":"International Delight"},
{"rank":65,"description":"Coffee","brand":"Folgers-Classic Roast Coffee Medium Blend"},
{"rank":66,"description":"Fresh Milk Semi-Skimmed","brand":"Daily Milk"},
{"rank":67,"description":"Coffee - Brewed, espresso","brand":""},
{"rank":68,"description":"Water - Municipal","brand":""},
{"rank":69,"description":"Coffee Instant (With Semi Skimmed Milk) & 1 Teaspoon","brand":"Home Prepared"},
{"rank":70,"description":"Semi-Skimmed Milk","brand":"Lidl"},
{"rank":71,"description":"2 Scrambled Eggs, Plain","brand":"Country Crock Margarine"},
{"rank":72,"description":"Tea With Semi Skimmed Milk","brand":"Tetley"},
{"rank":73,"description":"Honey Bunches of Oats With Almonds","brand":"Post"},
{"rank":74,"description":"1% Lowfat Milk","brand":"Schnucks"},
{"rank":75,"description":"Sugars - Brown","brand":""},
{"rank":76,"description":"Weetabix With 100ml Semi Skimmed Milk","brand":"Weetabix"},
{"rank":77,"description":"Biscuits - Plain or buttermilk, baked","brand":""},
{"rank":78,"description":"Cucumber - With peel, raw","brand":""},
{"rank":79,"description":"Butter - Unsalted","brand":""},
{"rank":80,"description":"Melons - Cantaloupe, raw","brand":""},
{"rank":81,"description":"Cup of Tea, Semi Skimmed Milk","brand":"Tetly"},
{"rank":82,"description":"White Coffee One Sugar","brand":"White Coffee One Sugar"},
{"rank":83,"description":"British Semi-skimmed Milk","brand":"Tesco"},
{"rank":84,"description":"Flora Light (New)","brand":"Flora"},
{"rank":85,"description":"Bread - Rye, toasted","brand":""},
{"rank":86,"description":"Coffee - White Semi-Skimmed","brand":"Nescafe"},
{"rank":87,"description":"Banana (7","brand":"Generic Usda"},
{"rank":88,"description":"White Bread (40g) Toasted With Flora Light Marg","brand":"Hovis (Uk"},
{"rank":89,"description":"Ham - Sliced, regular (approximately 11% fat)","brand":""},
{"rank":90,"description":"Coffee Instant (With Semi Skimmed Milk) & 1 Teaspoon","brand":"Home Prepared"},
{"rank":91,"description":"Egg White","brand":"Mc - Egg Whites"},
{"rank":92,"description":"Banane","brand":"Frucht"},
{"rank":93,"description":"Banana","brand":"Dole Costco"},
{"rank":94,"description":"Coffee With Semi Skimmed Milk & Sweeteners","brand":"Kenco"},
{"rank":95,"description":"Banana - Peeled","brand":"Fruit"},
{"rank":96,"description":"Nuts - Almonds","brand":""},
{"rank":97,"description":"Semi-Skimmed Milk","brand":"Generic"},
{"rank":98,"description":"Natural Cane Turbinado Sugar","brand":"Sugar In the Raw"},
{"rank":99,"description":"Carrots - Raw","brand":""},
{"rank":100,"description":"Cottage cheese - Lowfat, 2% milkfat","brand":""}];

